const fs = require('fs');
const path = require('path');
const { createTsConfig, createPackageJson, createReadme } = require('./common');

const group1 = require('./group1');
const group2 = require('./group2');
const group3 = require('./group3');
const group4 = require('./group4');
const group5 = require('./group5');

const allPackages = [...group1, ...group2, ...group3, ...group4, ...group5];
const rootDir = path.resolve(__dirname, '..', '..');

console.log(`Starting generation of ${allPackages.length} packages in ${rootDir}...`);

allPackages.forEach((pkg, index) => {
  const pkgDir = path.join(rootDir, pkg.folder);
  const srcDir = path.join(pkgDir, 'src');

  if (!fs.existsSync(pkgDir)) {
    fs.mkdirSync(pkgDir, { recursive: true });
  }
  if (!fs.existsSync(srcDir)) {
    fs.mkdirSync(srcDir, { recursive: true });
  }

  // 1. package.json
  const pkgJsonContent = createPackageJson({
    name: pkg.name,
    description: pkg.description,
    keywords: pkg.keywords
  });
  fs.writeFileSync(path.join(pkgDir, 'package.json'), pkgJsonContent, 'utf8');

  // 2. tsconfig.json
  fs.writeFileSync(path.join(pkgDir, 'tsconfig.json'), createTsConfig(), 'utf8');

  // 3. README.md
  const readmeContent = createReadme({
    name: pkg.name,
    description: pkg.description,
    category: pkg.category,
    usageCode: pkg.usageCode,
    apiList: pkg.apiList
  });
  fs.writeFileSync(path.join(pkgDir, 'README.md'), readmeContent, 'utf8');

  // 4. src/index.ts
  fs.writeFileSync(path.join(srcDir, 'index.ts'), pkg.code.trim() + '\n', 'utf8');

  console.log(`[${index + 1}/50] Generated: ${pkg.folder}`);
});

// Create Root .gitignore
const gitignoreContent = `# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
pnpm-debug.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# Dependency directories
node_modules/
jspm_packages/

# TypeScript cache
*.tsbuildinfo

# Build output
dist/
build/
.turbo/

# Environment variables
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# OS files
.DS_Store
Thumbs.db
`;
fs.writeFileSync(path.join(rootDir, '.gitignore'), gitignoreContent, 'utf8');

// Create Root package.json
const rootPackageJson = {
  name: 'npm-micro-utilities-factory',
  version: '1.0.0',
  private: true,
  description: 'Collection of 50 Production-Ready Micro / Utility npm packages',
  workspaces: allPackages.map((p) => p.folder),
  scripts: {
    "build:all": "turbo run build || npm run build:each",
    "test:all": "turbo run test || npm run test:each"
  },
  devDependencies: {
    tsup: '^8.3.5',
    typescript: '^5.7.2',
    vitest: '^2.1.8'
  }
};
fs.writeFileSync(path.join(rootDir, 'package.json'), JSON.stringify(rootPackageJson, null, 2), 'utf8');

// Create Root README.md
let masterReadme = `# 🚀 50 Micro / Utility NPM Packages Factory

> Bộ sưu tập **50 gói NPM Micro / Utility (Zero & Low Dependency)** giải quyết đúng bài toán thực tế, tối ưu trải nghiệm lập trình viên (Developer Experience), sẵn sàng build và publish lên GitHub & NPM.

---

## 📊 Thống Kê & Cấu Trúc Dự Án

- **Tổng số package:** 50
- **Ngôn ngữ:** 100% TypeScript
- **Target format:** Dual Build ESM (\`.mjs\`) & CommonJS (\`.cjs\`)
- **Type Declarations:** Đầy đủ \`.d.ts\` & Source Maps

---

## 📑 Danh Sách Chi Tiết 50 Packages

`;

const categories = [
  { name: 'I. Việt Nam Localization & Business Logic', list: group1 },
  { name: 'II. AI, LLM & Prompt Engineering Helpers', list: group2 },
  { name: 'III. System, Node.js & File Management Utilities', list: group3 },
  { name: 'IV. Frontend & React / Next.js Micro Components', list: group4 },
  { name: 'V. Computer Vision, IoT & Edge Streaming Helpers', list: group5 }
];

categories.forEach((cat) => {
  masterReadme += `### ${cat.name}\n\n`;
  masterReadme += `| # | Thư mục / Tên Package | Mô tả ngắn | Trạng thái |\n`;
  masterReadme += `|---|---|---|:---:|\n`;

  cat.list.forEach((pkg) => {
    masterReadme += `| **${pkg.folder.slice(0, 2)}** | [\`${pkg.name}\`](./${pkg.folder}) | ${pkg.description} | Ready ✅ |\n`;
  });

  masterReadme += `\n`;
});

masterReadme += `---

## 🛠️ Hướng Dẫn Phát Triển & Publish Lên NPM

### 1. Cài đặt môi trường trong từng package

\`\`\`bash
cd 01-vn-cccd-parser
npm install
npm run build
\`\`\`

### 2. Chạy Test

\`\`\`bash
npm test
\`\`\`

### 3. Đăng nhập và Publish lên NPM

\`\`\`bash
npm login
npm publish --access public
\`\`\`

---

## 📄 License

MIT © [Your Name](https://github.com)
`;

fs.writeFileSync(path.join(rootDir, 'README.md'), masterReadme, 'utf8');

console.log('\n✅ Successfully generated all 50 packages, root README.md, root package.json, and .gitignore!');
